---
images_ansible_name: ansible-core
images_ansible_version: latest

# Whether to run tests
run_tests: true

# Whether to remove the image after testing and publishing
remove_image: true

# Whether to remove the image afterwards
publish_image: false

# Whether to build the image
build_image: true

# Whether ara should be enabled and configured to record playbook results on an ara server
images_enable_ara: false
# Note: If running the ara server locally, this would be your interface IP (not 127.0.0.1 which is the container itself)
#       Your will need to add your interface IP in ARA_ALLOWED_HOSTS or in the server's settings.yaml
images_ara_api_server: "http://{{ ansible_default_ipv4['address'] }}:8000"
# images_ara_api_username:
# images_ara_api_password:

images_packages:
  - git
  - buildah
  - podman

images_venv: "{{ ansible_user_dir }}/.ansible/tmp/community_images_venv"
images_venv_cleanup: true
