- name: Basic integration tests
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Collect some facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!any"
          - date_time
          - distribution
          - dns
          - kernel
          - python

    - name: Install ps
      become: true
      ansible.builtin.package:
        name: procps-ng
        state: latest

    - name: Print running Ansible processes
      ansible.builtin.shell: ps fauxwww | grep -i ansible
      changed_when: false

    - name: Retrieve the installed version of ansible-core
      ansible.builtin.shell: pip show ansible-core | awk "/Version/ {print $2}"
      changed_when: false
      register: _installed_ansible_core

    - name: Retrieve the installed version of ansible with pip
      ansible.builtin.shell: pip show ansible | awk "/Version/ {print $2}"
      changed_when: false
      register: _ansible_version_pypi

  tasks:
    - name: Validate image
      assert:
        that:
          - ansible_distribution == "Fedora"
          - ansible_distribution_release == ""
          - ansible_distribution_version == "38"

