"""Tests for the Python requirements generator."""

from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path
from types import ModuleType

import pytest

SCRIPT_PATH = (
    Path(__file__).resolve().parents[1] / "scripts" / "generate_python_requirements.py"
)


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    """Load the requirements generator as a module."""
    spec = importlib.util.spec_from_file_location(
        "generate_python_requirements", SCRIPT_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load generator from {SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_missing_requirements_file_means_no_collections(
    generator: ModuleType, tmp_path: Path
) -> None:
    """Treat an absent Galaxy requirements file as an empty collection set."""
    assert generator.read_collection_requirements(tmp_path / "requirements.yml") == []


def test_render_requirements_sorts_dependencies(generator: ModuleType) -> None:
    """Render collection requirements in deterministic lexical order."""
    assert generator.render_requirements(
        [
            "xmltodict  # from collection ansible.utils",
            "netaddr>=0.10.1  # from collection ansible.utils",
            "jsonschema  # from collection ansible.utils",
        ]
    ) == (
        "# Generated from requirements.yml by "
        "../scripts/generate_python_requirements.py.\n"
        "#\n"
        "# Do not edit manually.\n"
        "\n"
        "jsonschema  # from collection ansible.utils\n"
        "netaddr>=0.10.1  # from collection ansible.utils\n"
        "xmltodict  # from collection ansible.utils\n"
    )


def test_parse_introspection_output_reads_python_requirements(
    generator: ModuleType,
) -> None:
    """Read Python requirements from Builder's structured YAML output."""
    output = """# Dependency data for /tmp/example
---
python:
  - xmltodict
  - netaddr>=0.10.1
system:
  - gcc [compile]
"""

    assert generator.parse_introspection_output(output) == [
        "xmltodict",
        "netaddr>=0.10.1",
    ]


def test_generate_without_collections_skips_galaxy_and_introspection(
    generator: ModuleType, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Compile a comment-only input without invoking collection tools."""
    (tmp_path / "requirements-constraints.in").write_text(
        "# constraints\n", encoding="utf-8"
    )
    (tmp_path / "requirements-explicit.in").write_text(
        "# explicit requirements\n", encoding="utf-8"
    )
    calls: list[tuple[list[str], Path | None]] = []

    def fake_run(
        command: list[str],
        *,
        cwd: Path | None = None,
        check: bool,
        capture_output: bool = False,
        text: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        calls.append((command, cwd))
        return subprocess.CompletedProcess(command, 0, stdout="", stderr="")

    monkeypatch.setattr(generator.subprocess, "run", fake_run)

    generator.generate_requirements(tmp_path)

    assert (tmp_path / "requirements.in").read_text(encoding="utf-8") == (
        "# Generated by ../scripts/generate_python_requirements.py.\n"
        "#\n"
        "# No collection Python dependencies.\n"
        "# Do not edit manually.\n"
    )
    assert calls == [
        (
            [
                "uv",
                "pip",
                "compile",
                "requirements.in",
                "requirements-explicit.in",
                "--constraints",
                "requirements-constraints.in",
                "--output-file",
                "requirements.txt",
                "--python-version",
                "3.14",
            ],
            tmp_path,
        )
    ]
