#!/usr/bin/env python3
"""Generate locked Python requirements for an execution environment."""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

# Python version provided by the Fedora 44 base image used by both EEs.
TARGET_PYTHON_VERSION = "3.14"

GENERATED_HEADER = (
    "# Generated from requirements.yml by "
    "../scripts/generate_python_requirements.py.\n"
    "#\n"
    "# Do not edit manually.\n"
)


def render_requirements(requirements: list[str]) -> str:
    """Render collection Python requirements deterministically.

    Args:
        requirements: Requirement expressions emitted by Ansible Builder.

    Returns:
        Generated ``requirements.in`` content ending in a newline.
    """
    ordered = sorted(requirements, key=str.casefold)
    if not ordered:
        return (
            "# Generated by ../scripts/generate_python_requirements.py.\n"
            "#\n"
            "# No collection Python dependencies.\n"
            "# Do not edit manually.\n"
        )
    requirements_block = "\n".join(ordered)
    return f"{GENERATED_HEADER}\n{requirements_block}\n"


def parse_introspection_output(output: str) -> list[str]:
    """Extract Python requirements from Ansible Builder's YAML output.

    Args:
        output: Structured output from ``ansible-builder introspect``.

    Returns:
        Python requirement expressions emitted by Builder.

    Raises:
        TypeError: If Builder's output has the wrong structure.
        ValueError: If Builder's output contains malformed YAML.
    """
    try:
        data: object = yaml.safe_load(output)
    except yaml.YAMLError as error:
        raise ValueError(
            "ansible-builder introspect returned malformed YAML"
        ) from error
    if not isinstance(data, dict):
        raise TypeError("ansible-builder introspect returned no YAML mapping")
    requirements: object = data.get("python")
    if not isinstance(requirements, list) or not all(
        isinstance(requirement, str) for requirement in requirements
    ):
        raise TypeError(
            "ansible-builder introspect returned an invalid 'python' requirement list"
        )
    return requirements


def read_collection_requirements(requirements_path: Path) -> list[object]:
    """Read collection declarations from a Galaxy requirements file.

    Args:
        requirements_path: Path to the optional ``requirements.yml`` file.

    Returns:
        Collection declarations, or an empty list when the file is absent.

    Raises:
        TypeError: If the requirements file has the wrong structure.
        ValueError: If the requirements file contains malformed YAML.
    """
    if not requirements_path.is_file():
        return []

    try:
        manifest: object = yaml.safe_load(requirements_path.read_text(encoding="utf-8"))
    except yaml.YAMLError as error:
        raise ValueError(f"{requirements_path}: malformed YAML") from error
    if not isinstance(manifest, dict):
        raise TypeError(f"{requirements_path}: expected a YAML mapping")

    collections: object = manifest.get("collections", [])
    if not isinstance(collections, list):
        raise TypeError(f"{requirements_path}: 'collections' must be a list")
    return collections


def discover_collection_requirements(
    requirements_path: Path, collection_root: Path
) -> list[str]:
    """Install collections and return their Builder-derived Python requirements.

    Args:
        requirements_path: Galaxy requirements file to install.
        collection_root: Temporary collection installation root.

    Returns:
        Python requirement expressions emitted by Ansible Builder.

    Raises:
        subprocess.CalledProcessError: If installation or introspection fails.
        ValueError: If Builder returns malformed structured output.
    """
    subprocess.run(
        [
            "ansible-galaxy",
            "collection",
            "install",
            "-r",
            str(requirements_path),
            "-p",
            str(collection_root),
            "--force",
        ],
        check=True,
    )
    result = subprocess.run(
        ["ansible-builder", "introspect", "--sanitize", str(collection_root)],
        check=True,
        capture_output=True,
        text=True,
    )
    return parse_introspection_output(result.stdout)


def compile_requirements(ee_directory: Path) -> None:
    """Resolve the generated input against the EE's target Python version.

    Args:
        ee_directory: Directory containing the generated and constraint inputs.

    Raises:
        subprocess.CalledProcessError: If dependency resolution fails.
    """
    subprocess.run(
        [
            "uv",
            "pip",
            "compile",
            "requirements.in",
            "requirements-explicit.in",
            "--constraints",
            "requirements-constraints.in",
            "--output-file",
            "requirements.txt",
            "--python-version",
            TARGET_PYTHON_VERSION,
        ],
        cwd=ee_directory,
        check=True,
    )


def generate_requirements(ee_directory: Path) -> None:
    """Generate locked Python requirements for an execution environment.

    Args:
        ee_directory: Directory containing the execution environment definition.

    Raises:
        FileNotFoundError: If the EE directory or constraints file does not exist.
        RuntimeError: If collection introspection or dependency resolution fails.
        TypeError: If an input or introspection result has the wrong structure.
        ValueError: If an input or introspection result contains malformed YAML.
    """
    if not ee_directory.is_dir():
        raise FileNotFoundError(
            f"execution environment directory not found: {ee_directory}"
        )

    constraints_path = ee_directory / "requirements-constraints.in"
    if not constraints_path.is_file():
        raise FileNotFoundError(
            f"required constraints file not found: {constraints_path}"
        )

    explicit_path = ee_directory / "requirements-explicit.in"
    if not explicit_path.is_file():
        raise FileNotFoundError(
            f"required explicit requirements file not found: {explicit_path}"
        )

    requirements_path = ee_directory / "requirements.yml"
    collections = read_collection_requirements(requirements_path)
    python_requirements: list[str] = []
    if collections:
        with tempfile.TemporaryDirectory(
            prefix="ansible-community-images-", dir="/tmp"
        ) as temporary_directory:
            python_requirements = discover_collection_requirements(
                requirements_path, Path(temporary_directory)
            )

    (ee_directory / "requirements.in").write_text(
        render_requirements(python_requirements), encoding="utf-8"
    )
    compile_requirements(ee_directory)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate locked Python requirements for an execution environment."
    )
    parser.add_argument(
        "ee_directory",
        type=Path,
        help="directory containing the execution environment definition",
    )
    return parser.parse_args()


def main() -> None:
    """Run the requirements generator CLI."""
    args = parse_args()
    try:
        generate_requirements(args.ee_directory.resolve())
    except (FileNotFoundError, TypeError, ValueError) as error:
        sys.exit(f"error: {error}")
    except subprocess.CalledProcessError as error:
        sys.exit(
            f"error: command failed with exit code {error.returncode}: "
            f"{' '.join(error.cmd)}"
        )


if __name__ == "__main__":
    main()
