---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.14-latest'

ansible_config: 'ansible.cfg'

dependencies:
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml
