---
- project:
    name: ansible-community/images
    default-branch: main
    check:
      jobs:
        - community-images-ansible-test-build
    post:
      jobs:
        - community-images-ansible-test-publish
    # Build, test and publish new images once every 24hrs
    # https://github.com/ansible/zuul-config/blob/893cd2e5fa9991078332e2b0d461336eaa5cf888/zuul.d/pipelines.yaml#L180-L203
    periodic:
      jobs:
        - community-images-ansible-test-publish
