---
- project:
    name: ansible-community/images
    default-branch: main
    check:
      jobs:
        - community-images-ansible-test-build
    post:
      jobs:
        - community-images-ansible-test-publish
